language:
  - ruby
rvm:
  - 2.2.2
install:
  - bundle install
  - npm install
  - cd client && npm run build
env:
  - export RAILS_ENV=test
script:
  - bundle exec rake db:schema:load
  - bundle exec rake
  - bundle exec rake lint
